Repository MixInn/MixIn_BE, pull requests merged in 2024-11, with the labels that each got.

#14 #12feat/profile
  src/main/java/com/sparta/mixin/domain/auth/config/WebSecurityConfig.java
  src/main/java/com/sparta/mixin/domain/auth/security/JwtAuthenticationFilter.java
  src/main/java/com/sparta/mixin/domain/auth/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/mixin/domain/auth/service/AuthService.java
  src/main/java/com/sparta/mixin/domain/auth/service/SmsCertification.java
  src/main/java/com/sparta/mixin/domain/auth/service/SmsServiceImpl.java
  src/main/java/com/sparta/mixin/domain/profile/controller/ProfileController.java
  src/main/java/com/sparta/mixin/domain/profile/dto/ProfileRequestDto.java
  src/main/java/com/sparta/mixin/domain/profile/dto/ProfileResponseDto.java
  src/main/java/com/sparta/mixin/domain/profile/entity/Interest.java
  src/main/java/com/sparta/mixin/domain/profile/entity/ParticipationType.java
  src/main/java/com/sparta/mixin/domain/profile/entity/Personality.java
  src/main/java/com/sparta/mixin/domain/profile/entity/Profile.java
  src/main/java/com/sparta/mixin/domain/profile/entity/ProfileRepository.java
  src/main/java/com/sparta/mixin/domain/profile/entity/ValueSystem.java
  src/main/java/com/sparta/mixin/domain/profile/service/ProfileService.java
  src/main/java/com/sparta/mixin/domain/user/entity/Interest.java
  src/main/java/com/sparta/mixin/domain/user/entity/ParticipationType.java
  src/main/java/com/sparta/mixin/domain/user/entity/Personality.java
  src/main/java/com/sparta/mixin/domain/user/entity/Profile.java
  src/main/java/com/sparta/mixin/domain/user/entity/ProfileValues.java
  src/main/java/com/sparta/mixin/domain/user/entity/UserRepository.java
  src/main/resources/application.properties
Labels: 🌟feat

#15 Feat/#11
  src/main/java/com/sparta/mixin/domain/community/bookmark/BookmarkService.java
  src/main/java/com/sparta/mixin/domain/community/comment/CommentService.java
  src/main/java/com/sparta/mixin/domain/community/comment/entity/CommunityComment.java
  src/main/java/com/sparta/mixin/domain/community/like/LikeService.java
  src/main/java/com/sparta/mixin/domain/community/meetpost/MeetPostController.java
  src/main/java/com/sparta/mixin/domain/community/meetpost/MeetPostService.java
  src/main/java/com/sparta/mixin/domain/community/meetpost/entity/MeetPost.java
  src/main/java/com/sparta/mixin/domain/community/publicpost/PublicPostRepository.java
  src/main/java/com/sparta/mixin/domain/community/publicpost/PublicPostService.java
  src/main/java/com/sparta/mixin/domain/image/ImageController.java
  src/main/java/com/sparta/mixin/domain/image/ImageRepository.java
  src/main/java/com/sparta/mixin/domain/image/ImageService.java
  src/main/java/com/sparta/mixin/domain/image/dto/ImageResponseDto.java
  src/main/java/com/sparta/mixin/domain/image/entity/Image.java
  src/main/java/com/sparta/mixin/domain/meet/service/MeetAuthorizationService.java
  src/main/java/com/sparta/mixin/domain/meet/service/MeetService.java
  src/main/java/com/sparta/mixin/global/exception/ErrorCode.java
Labels: 🌟feat, 🩹fix

#17 feat: 프로필 생성,조회 프로필 이미지 생성,수정,삭제 구현
  src/main/java/com/sparta/mixin/domain/profile/controller/ProfileController.java
  src/main/java/com/sparta/mixin/domain/profile/entity/Profile.java
  src/main/java/com/sparta/mixin/domain/profile/entity/ProfileRepository.java
  src/main/java/com/sparta/mixin/domain/profile/service/ProfileService.java
  src/main/java/com/sparta/mixin/domain/user/entity/User.java
  src/main/java/com/sparta/mixin/global/exception/ErrorCode.java
  src/main/resources/application.properties
Labels: 🌟feat

#20 #19fix/file
  src/main/java/com/sparta/mixin/domain/auth/config/WebSecurityConfig.java
  src/main/java/com/sparta/mixin/domain/auth/controller/AuthController.java
  src/main/java/com/sparta/mixin/domain/auth/dto/BasicInfoRequestDto.java
  src/main/java/com/sparta/mixin/domain/auth/service/AuthService.java
  src/main/java/com/sparta/mixin/domain/community/bookmark/BookmarkController.java
  src/main/java/com/sparta/mixin/domain/community/bookmark/BookmarkService.java
  src/main/java/com/sparta/mixin/domain/community/comment/CommentController.java
  src/main/java/com/sparta/mixin/domain/community/comment/CommentService.java
  src/main/java/com/sparta/mixin/domain/community/like/LikeController.java
  src/main/java/com/sparta/mixin/domain/community/like/LikeService.java
  src/main/java/com/sparta/mixin/domain/community/meetpost/MeetPostController.java
  src/main/java/com/sparta/mixin/domain/community/meetpost/MeetPostService.java
  src/main/java/com/sparta/mixin/domain/community/publicpost/PublicPostController.java
  src/main/java/com/sparta/mixin/domain/community/publicpost/PublicPostService.java
  src/main/java/com/sparta/mixin/domain/image/ImageController.java
  src/main/java/com/sparta/mixin/domain/image/ImageService.java
  src/main/java/com/sparta/mixin/domain/meet/controller/MeetController.java
  src/main/java/com/sparta/mixin/domain/meetannouncement/controller/MeetAnnouncementController.java
  src/main/java/com/sparta/mixin/domain/meetapplication/controller/MeetApplicationController.java
  src/main/java/com/sparta/mixin/domain/profile/controller/ProfileController.java
  src/main/java/com/sparta/mixin/domain/user/controller/UserController.java
  src/main/java/com/sparta/mixin/domain/user/service/UserService.java
  src/main/java/com/sparta/mixin/global/jwt/JwtUtil.java
  src/main/java/com/sparta/mixin/global/security/JwtAuthenticationFilter.java
  src/main/java/com/sparta/mixin/global/security/JwtAuthorizationFilter.java
  src/main/java/com/sparta/mixin/global/security/UserDetailsImpl.java
  src/main/java/com/sparta/mixin/global/security/UserDetailsServiceImpl.java
  uploads/profileImages/61d87994-6d3a-429a-a478-f8e57bbad95a_스크린샷 2024-07-25 오후 5.59.30.png
Labels: 🩹fix

#24 Feat/#23
  src/main/java/com/sparta/mixin/domain/post/PostService.java
  src/main/java/com/sparta/mixin/domain/post/bookmark/BookmarkService.java
  src/main/java/com/sparta/mixin/domain/post/comment/CommentService.java
  src/main/java/com/sparta/mixin/domain/post/dto/MeetNoticeResponseDto.java
  src/main/java/com/sparta/mixin/domain/post/dto/MeetPostResponseDto.java
  src/main/java/com/sparta/mixin/domain/post/dto/PostResponseDto.java
  src/main/java/com/sparta/mixin/domain/post/dto/PublicPostResponseDto.java
  src/main/java/com/sparta/mixin/domain/post/entity/MeetNotice.java
  src/main/java/com/sparta/mixin/domain/post/entity/MeetPost.java
  src/main/java/com/sparta/mixin/domain/post/entity/Post.java
  src/main/java/com/sparta/mixin/domain/post/entity/PublicPost.java
  src/main/java/com/sparta/mixin/domain/post/like/LikeService.java
  src/main/java/com/sparta/mixin/domain/post/meetnotice/MeetNoticeController.java
  src/main/java/com/sparta/mixin/domain/post/meetnotice/MeetNoticeService.java
  src/main/java/com/sparta/mixin/domain/post/meetpost/MeetPostController.java
  src/main/java/com/sparta/mixin/domain/post/meetpost/MeetPostService.java
  src/main/java/com/sparta/mixin/domain/post/noticeread/NoticeRead.java
  src/main/java/com/sparta/mixin/domain/post/noticeread/NoticeReadRepository.java
  src/main/java/com/sparta/mixin/domain/post/publicpost/PublicPostController.java
  src/main/java/com/sparta/mixin/domain/post/publicpost/PublicPostRepository.java
  src/main/java/com/sparta/mixin/domain/post/publicpost/PublicPostService.java
Labels: 🌟feat

#26 Feat/#25
  src/main/java/com/sparta/mixin/domain/post/PostService.java
  src/main/java/com/sparta/mixin/domain/post/dto/PostResponseDto.java
  src/main/java/com/sparta/mixin/domain/post/entity/MeetPost.java
  src/main/java/com/sparta/mixin/domain/post/entity/Post.java
  src/main/java/com/sparta/mixin/domain/post/entity/PublicPost.java
  src/main/java/com/sparta/mixin/domain/post/meetnotice/MeetNoticeController.java
  src/main/java/com/sparta/mixin/domain/post/meetpost/MeetPostController.java
  src/main/java/com/sparta/mixin/domain/post/meetpost/MeetPostRepository.java
  src/main/java/com/sparta/mixin/domain/post/publicpost/PublicPostController.java
  src/main/java/com/sparta/mixin/domain/post/publicpost/PublicPostRepository.java
Labels: 🌟feat

#28 Feat/#27
  src/main/java/com/sparta/mixin/domain/post/comment/CommentController.java
  src/main/java/com/sparta/mixin/domain/post/comment/CommentService.java
  src/main/java/com/sparta/mixin/domain/post/comment/dto/ReplyCommentResponseDto.java
  src/main/java/com/sparta/mixin/domain/post/comment/entity/PostComment.java
  src/main/java/com/sparta/mixin/domain/post/replycomment/ReplyComment.java
  src/main/java/com/sparta/mixin/domain/post/replycomment/ReplyCommentController.java
  src/main/java/com/sparta/mixin/domain/post/replycomment/ReplyCommentRepository.java
  src/main/java/com/sparta/mixin/domain/post/replycomment/ReplyCommentService.java
Labels: 🌟feat

#30 Feat/#29
  src/main/java/com/sparta/mixin/domain/post/PostService.java
  src/main/java/com/sparta/mixin/domain/post/dto/PostRequestDto.java
  src/main/java/com/sparta/mixin/domain/post/entity/Post.java
  src/main/java/com/sparta/mixin/domain/post/meetnotice/MeetNoticeController.java
  src/main/java/com/sparta/mixin/domain/post/meetnotice/MeetNoticeService.java
  src/main/java/com/sparta/mixin/domain/post/meetpost/MeetPostController.java
  src/main/java/com/sparta/mixin/domain/post/meetpost/MeetPostService.java
  src/main/java/com/sparta/mixin/domain/post/publicpost/PublicPostController.java
  src/main/java/com/sparta/mixin/domain/post/publicpost/PublicPostService.java
  src/main/java/com/sparta/mixin/domain/post/vote/PostVoteController.java
  src/main/java/com/sparta/mixin/domain/post/vote/PostVoteService.java
  src/main/java/com/sparta/mixin/domain/post/vote/dto/VoteOptionResponseDto.java
  src/main/java/com/sparta/mixin/domain/post/vote/dto/VoteRequestDto.java
  src/main/java/com/sparta/mixin/domain/post/vote/dto/VoteResponseDto.java
  src/main/java/com/sparta/mixin/domain/post/vote/entity/PostVote.java
  src/main/java/com/sparta/mixin/domain/post/vote/entity/VoteOption.java
  src/main/java/com/sparta/mixin/domain/post/vote/entity/VoteResult.java
  src/main/java/com/sparta/mixin/domain/post/vote/repository/PostVoteRepository.java
  src/main/java/com/sparta/mixin/domain/post/vote/repository/VoteOptionRepository.java
  src/main/java/com/sparta/mixin/domain/post/vote/repository/VoteResultRepository.java
  src/main/java/com/sparta/mixin/global/exception/ErrorCode.java
Labels: 🌟feat

#32 Feat/#31
  src/main/java/com/sparta/mixin/domain/image/ImageRepository.java
  src/main/java/com/sparta/mixin/domain/image/dto/ImageResponseDto.java
  src/main/java/com/sparta/mixin/domain/post/PostService.java
  src/main/java/com/sparta/mixin/domain/post/comment/CommentService.java
  src/main/java/com/sparta/mixin/domain/post/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/mixin/domain/post/comment/dto/ReplyCommentResponseDto.java
  src/main/java/com/sparta/mixin/domain/post/dto/MeetNoticeResponseDto.java
  src/main/java/com/sparta/mixin/domain/post/dto/MeetPostResponseDto.java
  src/main/java/com/sparta/mixin/domain/post/dto/PostResponseDto.java
  src/main/java/com/sparta/mixin/domain/post/dto/PublicPostResponseDto.java
  src/main/java/com/sparta/mixin/domain/post/replycomment/ReplyCommentController.java
  src/main/java/com/sparta/mixin/domain/post/vote/PostVoteController.java
  src/main/java/com/sparta/mixin/domain/post/vote/PostVoteService.java
  src/main/java/com/sparta/mixin/domain/post/vote/dto/VoteResponseDto.java
Labels: ♻️refactor

#43 Feat/#42
  src/main/java/com/sparta/mixin/domain/post/PostService.java
  src/main/java/com/sparta/mixin/domain/post/bookmark/BookmarkRepository.java
  src/main/java/com/sparta/mixin/domain/post/dto/MeetPostResponseDto.java
  src/main/java/com/sparta/mixin/domain/post/dto/PostResponseDto.java
  src/main/java/com/sparta/mixin/domain/post/dto/PublicPostResponseDto.java
  src/main/java/com/sparta/mixin/domain/post/meetnotice/MeetNoticeService.java
  src/main/java/com/sparta/mixin/domain/post/meetpost/MeetPostService.java
  src/main/java/com/sparta/mixin/domain/post/publicpost/PublicPostService.java
  src/main/java/com/sparta/mixin/domain/post/vote/PostVoteService.java
  src/main/java/com/sparta/mixin/domain/post/vote/dto/VoteResponseDto.java
  src/main/java/com/sparta/mixin/domain/post/vote/repository/VoteResultRepository.java
Labels: 🩹fix
